### ISSUE TITLE
Low-memory conditions issues

### ISSUE THREAD

**Issue by ligen-ua** [oleks-yehorov/PathHider#1]
It's OK not to have enough memory in kernel mode, the driver should never raise exceptions on low-memory conditions:

```
inline void* __cdecl operator new(unsigned __int64 size) 
{
....
    else
    {
        ExRaiseStatus(STATUS_NO_MEMORY);
    }
    return result;
}
```

The client side should handle the operation result.
I would recommend also to check with Driver Verifier with low resource simulation check enabled.

**Comment by oleks-yehorov** [comment]
It is a good point, thank you. I did not realize that "ExRaiseStatus" is actually an exception. I have wrapped the allocations in __try __except blocks and did some testing with Driver Verifier with low resource simulation check enabled. Is it a good fix?
