### ISSUE TITLE
Lack of try/except  (or proper parameter capture)

### ISSUE THREAD

**Issue by ligen-ua** [oleks-yehorov/PathHider#2]
PortMessageNotify function lacks some try/except logic, see MSDN about communication ports:

> Note that InputBuffer is a pointer to a raw, unlocked user-mode buffer. This pointer is valid only in the context of the user-mode process and must only be accessed from within a try/except block.

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcreatecommunicationport

**Comment by oleks-yehorov** [comment]
Fixed by the same fix as for issue #1
